-- AlterTable
ALTER TABLE "N8n" ADD COLUMN IF NOT EXISTS "systemMessage" TEXT;
ALTER TABLE "N8n" ADD COLUMN IF NOT EXISTS "contextWindowSize" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "N8n" ADD COLUMN IF NOT EXISTS "fallbackMessage" VARCHAR(500);