import { JSONSchema7 } from 'json-schema';
import { v4 } from 'uuid';

export const rateLimiterConfigSchema: JSONSchema7 = {
  $id: v4(),
  type: 'object',
  properties: {
    enabled: { type: 'boolean', default: true },
    messagesPerSecond: {
      type: 'integer',
      minimum: 1,
      maximum: 10,
      description: 'Maximum messages per second',
    },
    messagesPerMinute: {
      type: 'integer',
      minimum: 1,
      maximum: 120,
      description: 'Maximum messages per minute',
    },
    messagesPerHour: {
      type: 'integer',
      minimum: 1,
      maximum: 5000,
      description: 'Maximum messages per hour',
    },
    messagesPerDay: {
      type: 'integer',
      minimum: 1,
      maximum: 50000,
      description: 'Maximum messages per day',
    },
    delayBetweenMessages: {
      type: 'integer',
      minimum: 0,
      maximum: 60000,
      description: 'Delay between messages in milliseconds',
    },
    maxRetries: {
      type: 'integer',
      minimum: 1,
      maximum: 10,
      description: 'Maximum retry attempts when rate limit is hit',
    },
    backoffMultiplier: {
      type: 'number',
      minimum: 1,
      maximum: 5,
      description: 'Exponential backoff multiplier',
    },
    humanLikeBehavior: {
      type: 'boolean',
      default: false,
      description: 'Enable human-like behavior to avoid bot detection',
    },
    typingSpeedMsPerChar: {
      type: 'integer',
      minimum: 10,
      maximum: 200,
      default: 50,
      description: 'Typing speed in milliseconds per character',
    },
    minRandomVariation: {
      type: 'integer',
      minimum: 0,
      maximum: 1000,
      default: 100,
      description: 'Minimum random delay variation in milliseconds',
    },
    maxRandomVariation: {
      type: 'integer',
      minimum: 0,
      maximum: 5000,
      default: 500,
      description: 'Maximum random delay variation in milliseconds',
    },
    maxTypingDelayMs: {
      type: 'integer',
      minimum: 0,
      maximum: 10000,
      default: 2000,
      description: 'Maximum typing delay cap in milliseconds',
    },
    markAsReadBeforeSend: {
      type: 'boolean',
      default: false,
      description: 'Mark message as read before sending',
    },
    readMessages: {
      type: 'boolean',
      default: false,
      description: 'Mark incoming messages as read before sending reply',
    },
    maxMessagesToRead: {
      type: 'integer',
      minimum: 1,
      maximum: 100,
      default: 20,
      description: 'Maximum number of incoming messages to mark as read at once',
    },
    randomDelayBeforeReadMin: {
      type: 'integer',
      minimum: 0,
      maximum: 10000,
      default: 1000,
      description: 'Minimum delay before marking message as read (ms)',
    },
    randomDelayBeforeReadMax: {
      type: 'integer',
      minimum: 0,
      maximum: 10000,
      default: 3000,
      description: 'Maximum delay before marking message as read (ms)',
    },
    randomDelayBeforeReplyMin: {
      type: 'integer',
      minimum: 0,
      maximum: 30000,
      default: 2000,
      description: 'Minimum random delay before starting to type (ms)',
    },
    randomDelayBeforeReplyMax: {
      type: 'integer',
      minimum: 0,
      maximum: 30000,
      default: 8000,
      description: 'Maximum random delay before starting to type (ms)',
    },
  },
};
